### ISSUE TITLE
swap button function not working

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#10]
user firested123 | fb with uid (974670215679983676) reported reasons why swap buttons are not working.
Text link https://discord.com/channels/1294483466079047720/1314629564982624348/1318475282314952754

**Comment by ESSENTIALSAM** [comment]
uid 974670215679983676
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1318475282314952754

**Comment by ARitz-Cracker** [comment]
The CSP has no relationship with the current issues with the swap app
