### ISSUE TITLE
token swaps error

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#11]
user Don11 with uid (1265476096074321970) reported that test token swap from TKA to others is showing error, TKB to TKA success, but to others error. 
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1318484097382748213

**Comment by ESSENTIALSAM** [comment]
uid: 1265476096074321970
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1318484097382748213

**Comment by ARitz-Cracker** [comment]
Seems like a duplicate of #1
