### ISSUE TITLE
swap error

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#12]
user Don11 with uid (1265476096074321970) reported that token  tk abcd swap to eth keeps failing.
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1318483299869528095

**Comment by ESSENTIALSAM** [comment]
uid: 1265476096074321970
text link:  https://discord.com/channels/1294483466079047720/1314629564982624348/1318483299869528095

**Comment by ARitz-Cracker** [comment]
Seems like a duplicate of #6
