### ISSUE TITLE
extended faucet claim hour

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#13]
user Tanjir⊙ 💜 ⦿ ✧ with uid (1122606768929906779) reported that faucet claim hour was extended without initial daily claim done yet.
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1317896837390401598

**Comment by ESSENTIALSAM** [comment]
uid: 1122606768929906779
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1317896837390401598

**Comment by ARitz-Cracker** [comment]
The faucet cooldown time isn't 24hr, it's 36hr. Works as intended.
