### ISSUE TITLE
delay in high volume transaction

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#14]
user Valexaa with uid (848054900050886666) reported that it takes a bit longer to confirm the tx if the amount's high.

text link: https://discord.com/channels/1294483466079047720/1294483466607394827/1318646474048798752

**Comment by ESSENTIALSAM** [comment]
uid: 848054900050886666
text link: https://discord.com/channels/1294483466079047720/1294483466607394827/1318646474048798752

**Comment by ARitz-Cracker** [comment]
This isn't really something we can improve upon, anything regarding potentially long confirmation times is the monad team's job
