### ISSUE TITLE
error in pairing tokens

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#3]
user 31 with ID 922628838821859348 (https://discord.com/channels/1294483466079047720/1314629564982624348/1318177304438116453) reported that some tokens can not be paired for swapping.

**Comment by ESSENTIALSAM** [comment]
User ID: 922628838821859348 
Link to text: https://discord.com/channels/1294483466079047720/1314629564982624348/1318177304438116453

**Comment by ARitz-Cracker** [comment]
duplicate of https://github.com/mace-ag/swaps-app-issues/issues/1
