### ISSUE TITLE
swap buuton not workinng

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#4]
user big with UID (249939063551819777) reported on discord that swap buttons are not working.
kindly see link to text here https://discord.com/channels/1294483466079047720/1314629564982624348/1317957019285586021

**Comment by ESSENTIALSAM** [comment]
uid : 249939063551819777
link to text: https://discord.com/channels/1294483466079047720/1314629564982624348/1317957019285586021

**Comment by ARitz-Cracker** [comment]
Subsequent messages seem to imply that this is due to the known slippage issue which wasn't originally reported by this user. not the button itself not working
