### ISSUE TITLE
bugged site on ios

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#5]
user alchimedis with uid (715203024946987139) reported that the site is buggy on ion
Link to text: https://discord.com/channels/1294483466079047720/1314629564982624348/1317744473869910047

**Comment by ESSENTIALSAM** [comment]
uid: 715203024946987139
link to text: https://discord.com/channels/1294483466079047720/1314629564982624348/1317744473869910047

**Comment by ARitz-Cracker** [comment]
Not enough information is provided to warrant an investigation, follow-up messages imply that the issue is actually with ones that are already reported.
